### ISSUE TITLE
Add international data policy examples

### ISSUE THREAD

**Issue by chennesy** [ucla-imls-open-sci/dmp101#3]
As a follow up to the discussion at the March 14 meeting with the LC Curriculum Advisory Committee:

Add examples of relevant non-US data policies and laws to the lesson (e.g., the GDPR for the EU and/or the POPI Act for S. Africa). These could be added to the lesson where they're relevant and/or incorporated in the instructor notes. Overall, before moving to the Library Carpentry repo, the lesson should be edited to ensure it's addressed to an international audience.

**Comment by jt14den** [comment]
moved to new lesson location on LC
